### PR TITLE
Reformat imports to improve readability

### PR DESCRIPTION
**Pull request by knkski**
Groups imports into `std`, external, and internal dependencies

Signed-off-by: Kenneth Koski <knkski@bitwise.io>

### CODE REVIEW

**Comment by knkski** [comment]
@ltseeley: Right now we've got groups of dependencies broken up (see the `std::*` imports in `config.rs`), and groups of imports in different orders across files (sometimes `std` is first, sometimes it's not). Would you agree that we should at least fix those issues?

As far as one group vs multiple, it seems simpler to group them all into one and let `cargo fmt` handle the rest. There's then no bikeshedding about how to group imports, and which order the groups go in. There's also less manual verification that the style isn't being violated in code reviews (we just need to check that all imports are in one group, `cargo fmt` will verify the rest). That being said, I don't feel particularly strongly about this second bit. Does anyone else have strong opinions on this?

**Comment by agunde406** [comment]
I prefer to group the imports by standard modules, external crates, and our code. This helps with readability of the imports.

**Comment by peterschwarz** [comment]
While I can see the merits of the readability comments the others have added, I'm more inclined to agree with the "let `rustfmt` sort them" argument.  As an open source project, with a growing number of contributors with various native languages, one person's readability ordering is another person's noise.  `rustfmt` removes the need for that discussion and makes it a build server decision.

Now, if `rustfmt` could also join all the imports from the same module into a single instance of the bracket syntax, that would be something to clean up another area of bikeshedding...

**Comment by vaporos** [comment]
I think it would be great to have a single approach overall. I don't think grouping them into a single group is necessarily the best approach. The three groups Andi mentioned are the three I would normally categorize and seems clearer to me, with maybe a slight modification - standard language, external crates, and internal project. (The difference being that it's not about whether we wrote it, but whether it's part of the project.)

**Comment by agunde406** [comment]
What Shawn said about internal project is what I had intended in my first comment

**Comment by knkski** [comment]
@peterschwarz: That option exists in nightly:

https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#merge_imports

**Comment by knkski** [comment]
At the risk of proposing a solution that's hated equally by everyone, with the release of Rust 1.30, we can prefix external code with `crate::`, internal code with `super::`, leave `std::` unprefixed, and then group everything into one big group and let `rustfmt` take care of sorting everything. It will sort `super::`, then `crate::`, then everything else (i.e. `std::`). I've pushed up a commit that enacts this change for PBFT so that people can see how they feel about it.

**Comment by bridger-herman** [comment]
I would tend to agree with @agunde406 and @vaporos about not having everything as one giant list of imports, but separating them into groups of language, crate, and internal dependencies. Overall I don't hate the `crate::` and `super::` prefixes though.

**Comment by knkski** [comment]
Updated this PR to group the imports by `std`, external, and internal

**Pull request merged**
